"""
Compatibility module - re-exports from middleware.config.constants.
This file is deprecated. Use: from middleware.config import constants
"""
from middleware.config import constants

TWELVE_DATA_API_URL = constants.TWELVE_DATA_API_URL
TWELVE_DATA_CREDIT_LIMIT = constants.TWELVE_DATA_CREDIT_LIMIT
TWELVE_DATA_CREDIT_EMERGENCY_THRESHOLD = constants.TWELVE_DATA_CREDIT_EMERGENCY_THRESHOLD
FINNHUB_API_KEY = constants.FINNHUB_API_KEY
TRADERMADE_API_KEY = constants.TRADERMADE_API_KEY
ALPHA_VANTAGE_API_KEY = constants.ALPHA_VANTAGE_API_KEY
FOREXCOM_USERNAME = constants.FOREXCOM_USERNAME
FOREXCOM_PASSWORD = constants.FOREXCOM_PASSWORD
FOREXCOM_APP_KEY = constants.FOREXCOM_APP_KEY
TIMEZONE = constants.TIMEZONE
DEFAULT_INTERVAL = constants.DEFAULT_INTERVAL
MAX_INTERVAL = constants.MAX_INTERVAL
MODEL_PARAMS = constants.MODEL_PARAMS
MODEL_FEATURES = constants.MODEL_FEATURES
ML_TARGET_HORIZON_LOW_VOL = constants.ML_TARGET_HORIZON_LOW_VOL
ML_TARGET_HORIZON_HIGH_VOL = constants.ML_TARGET_HORIZON_HIGH_VOL
ML_TARGET_HORIZON_NORMAL_VOL = constants.ML_TARGET_HORIZON_NORMAL_VOL
PROBA_THRESHOLD_LONG = constants.PROBA_THRESHOLD_LONG
PROBA_THRESHOLD_SHORT = constants.PROBA_THRESHOLD_SHORT
RSI_OVERBOUGHT_THRESHOLD = constants.RSI_OVERBOUGHT_THRESHOLD
RSI_SOLD_THRESHOLD = constants.RSI_SOLD_THRESHOLD
MIN_VOLATILITY_PERCENT = constants.MIN_VOLATILITY_PERCENT
CONTRARIAN_CONFIDENCE_THRESHOLD = constants.CONTRARIAN_CONFIDENCE_THRESHOLD
MIN_CONFIDENCE_THRESHOLD = constants.MIN_CONFIDENCE_THRESHOLD
ATR_MULTIPLIER_DEFAULT = constants.ATR_MULTIPLIER_DEFAULT
ATR_MULTIPLIER_HIGH_CONFIDENCE = constants.ATR_MULTIPLIER_HIGH_CONFIDENCE
BASE_RISK_REWARD_RATIO = constants.BASE_RISK_REWARD_RATIO
HIGH_CONFIDENCE_RISK_REWARD_RATIO = constants.HIGH_CONFIDENCE_RISK_REWARD_RATIO
MODEL_FILE_PATH = constants.MODEL_FILE_PATH

__all__ = [
    "TWELVE_DATA_API_URL",
    "TWELVE_DATA_CREDIT_LIMIT",
    "TWELVE_DATA_CREDIT_EMERGENCY_THRESHOLD",
    "FINNHUB_API_KEY",
    "TRADERMADE_API_KEY",
    "ALPHA_VANTAGE_API_KEY",
    "FOREXCOM_USERNAME",
    "FOREXCOM_PASSWORD",
    "FOREXCOM_APP_KEY",
    "TIMEZONE",
    "DEFAULT_INTERVAL",
    "MAX_INTERVAL",
    "MODEL_PARAMS",
    "MODEL_FEATURES",
    "ML_TARGET_HORIZON_LOW_VOL",
    "ML_TARGET_HORIZON_HIGH_VOL",
    "ML_TARGET_HORIZON_NORMAL_VOL",
    "PROBA_THRESHOLD_LONG",
    "PROBA_THRESHOLD_SHORT",
    "RSI_OVERBOUGHT_THRESHOLD",
    "RSI_SOLD_THRESHOLD",
    "MIN_VOLATILITY_PERCENT",
    "CONTRARIAN_CONFIDENCE_THRESHOLD",
    "MIN_CONFIDENCE_THRESHOLD",
    "ATR_MULTIPLIER_DEFAULT",
    "ATR_MULTIPLIER_HIGH_CONFIDENCE",
    "BASE_RISK_REWARD_RATIO",
    "HIGH_CONFIDENCE_RISK_REWARD_RATIO",
    "MODEL_FILE_PATH",
]
