from dataclasses import dataclass, field
from typing import Optional, Dict, Any

@dataclass
class Signal:
    """
    Standardized trading signal generated by strategies.
    """
    strategy: str
    symbol: str
    direction: str  # "LARGO" or "CORTO"
    entry_price: float
    stop_loss: float
    take_profit: float
    sl_distance: float
    confidence: float
    setup: str
    status: str
    candleTime: str
    intervalo: str
    take_profit2: Optional[float] = None
    take_profit3: Optional[float] = None
    risk_factor: float = 1.0
    is_adjustment: bool = False
    break_even: Optional[float] = None
    
    # Metrics for building alerts and logging
    riesgo_pips: Optional[float] = None
    rr_ratio: Optional[float] = None
    profit: Optional[float] = None # Risk in USD (will be calculated by engine)
    
    size: Optional[float] = None
    
    # Additional strategy-specific metadata
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def __post_init__(self):
        """Normaliza la dirección para garantizar consistencia interna."""
        if self.direction:
            self.direction = self.direction.strip().upper()

    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary for compatibility with legacy components."""
        return {
            "strategy": self.strategy,
            "symbol": self.symbol,
            "direction": self.direction,
            "entryPrice": self.entry_price,
            "stopLoss": self.stop_loss,
            "takeProfit": self.take_profit,
            "takeProfit2": self.take_profit2,
            "takeProfit3": self.take_profit3,
            "slDistance": self.sl_distance,
            "riesgo_pips": self.riesgo_pips,
            "rr_ratio": self.rr_ratio,
            "confidence": self.confidence,
            "setup": self.setup,
            "status": self.status,
            "candleTime": self.candleTime,
            "intervalo": self.intervalo,
            "profit": self.profit,
            "size": self.size,
            "is_adjustment": self.is_adjustment,
            "break_even": self.break_even,
            **self.metadata
        }

