from dataclasses import dataclass, field
from typing import Optional, Dict, Any

@dataclass
class Signal:
    """
    Standardized trading signal generated by strategies.
    """
    strategy: str
    symbol: str
    direction: str  # "LARGO" or "CORTO"
    entry_price: float
    stop_loss: float
    take_profit: float
    sl_distance: float
    confidence: float
    setup: str
    status: str
    candle_time: str
    intervalo: str
    
    # Metrics for building alerts and logging
    riesgo_pips: Optional[float] = None
    rr_ratio: Optional[float] = None
    profit: Optional[float] = None # Risk in USD (will be calculated by engine)
    
    # Additional strategy-specific metadata
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary for compatibility with legacy components."""
        return {
            "strategy": self.strategy,
            "symbol": self.symbol,
            "direction": self.direction,
            "entryPrice": self.entry_price,
            "stopLoss": self.stop_loss,
            "takeProfit": self.take_profit,
            "slDistance": self.sl_distance,
            "riesgo_pips": self.riesgo_pips,
            "rr_ratio": self.rr_ratio,
            "confidence": self.confidence,
            "setup": self.setup,
            "status": self.status,
            "candle_time": self.candle_time,
            "intervalo": self.intervalo,
            "profit": self.profit,
            **self.metadata
        }
